# Generated by Django 4.2.23 on 2025-08-14 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userwatchhistory',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['tmdb_id', 'created_at'], name='movies_movi_tmdb_id_fc8100_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'release_date'], name='movies_movi_title_20a8c3_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['vote_average', 'vote_count'], name='movies_movi_vote_av_c456df_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'created_at'], name='movies_user_user_id_effc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['movie', 'created_at'], name='movies_user_movie_i_b2fff7_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchhistory',
            index=models.Index(fields=['user', 'watched_at'], name='movies_user_user_id_9ebc62_idx'),
        ),
        migrations.AddIndex(
            model_name='userwatchhistory',
            index=models.Index(fields=['movie', 'watched_at'], name='movies_user_movie_i_874023_idx'),
        ),
    ]
