# Generated by Django 4.2.23 on 2025-08-14 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_movie_created_at_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userwatchhistory',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='userwatchhistory',
            index=models.Index(fields=['user', 'movie'], name='movies_user_user_id_fa7a1b_idx'),
        ),
    ]
