# Generated by Django 4.2.23 on 2025-08-14 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_alter_userwatchhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark Theme'), ('light', 'Light Theme'), ('auto', 'Auto (System)')], default='dark', max_length=10)),
                ('default_view', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View')], default='grid', max_length=10)),
                ('movies_per_page', models.IntegerField(choices=[(10, '10'), (20, '20'), (30, '30'), (50, '50')], default=20)),
                ('preferred_genres', models.JSONField(blank=True, default=list)),
                ('min_rating', models.FloatField(default=0.0, help_text='Minimum movie rating to show')),
                ('max_rating', models.FloatField(default=10.0, help_text='Maximum movie rating to show')),
                ('min_release_year', models.IntegerField(default=1900, help_text='Earliest release year to show')),
                ('max_release_year', models.IntegerField(default=2030, help_text='Latest release year to show')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian')], default='en', max_length=5)),
                ('max_content_rating', models.CharField(choices=[('G', 'G - General Audiences'), ('PG', 'PG - Parental Guidance'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'R - Restricted'), ('NC-17', 'NC-17 - Adults Only')], default='R', max_length=10)),
                ('public_watch_history', models.BooleanField(default=False, help_text='Allow others to see your watch history')),
                ('public_favorites', models.BooleanField(default=False, help_text='Allow others to see your favorites')),
                ('public_profile', models.BooleanField(default=True, help_text='Make your profile visible to others')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('new_releases_notifications', models.BooleanField(default=True, help_text='Get notified about new releases')),
                ('recommendation_notifications', models.BooleanField(default=True, help_text='Receive movie recommendations')),
                ('weekly_summary', models.BooleanField(default=False, help_text='Receive weekly watching summary')),
                ('auto_add_to_history', models.BooleanField(default=True, help_text='Automatically add viewed movies to watch history')),
                ('show_adult_content', models.BooleanField(default=False, help_text='Show adult/mature content')),
                ('data_saver_mode', models.BooleanField(default=False, help_text='Use lower quality images to save data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
