# Generated by Django 4.2.23 on 2025-08-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20250814_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_genres',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
