# Generated by Django 4.2.23 on 2025-08-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_userpreferences_preferred_genres'),
    ]

    operations = [
    ]
