# Generated by Django 4.2.23 on 2025-08-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20250814_1942'),
    ]

    operations = [
        # Remove unnecessary fields from UserPreferences
        migrations.RemoveField(
            model_name='userpreferences',
            name='max_rating',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='min_release_year',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='max_release_year',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='max_content_rating',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='public_watch_history',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='public_favorites',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='public_profile',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='new_releases_notifications',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='recommendation_notifications',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='weekly_summary',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='show_adult_content',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='data_saver_mode',
        ),
    ]
